version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
      - ./data/db:/data/
    environment:
      - LANGUAGE=${LANGUAGE}
      - POSTGRES_USER=gopoker
      - POSTGRES_PASSWORD=gopoker!12345
      - POSTGRES_DB=db

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/usr/src/gopoker/src

  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    command: air
    volumes:
      - ./data/backend:/data
      - ./backend:/usr/src/gopoker
      - upload_data_dev:/var/uploads
    ports:
      - 8080:8080
    environment:
      - LANGUAGE=${LANGUAGE}
      - REQUESTS_PER_MIN=10
      - DB_USER=gopoker
      - DB_PASSWORD=gopoker!12345
      - DB_HOST=db
      - DB_TEST_HOST=db-test
      - DB_PORT=5432
      - DB_DATABASE=db
      - DB_TEST_DATABASE=db_tests
      - COOKIE_SECRET=sign_the_cookie
      - LISTEN_PORT=:8080
      - GAME_PLAYER_CAP=3
      - CORS_TRUSTED_ORIGINS=http://localhost:3000
      - GIN_MODE=release
      - FILE_UPLOAD_PATH=/var/uploads
      - FILE_UPLOAD_TYPE=local
    depends_on:
      - db
      - frontend

volumes:
  postgres_data_dev:
  upload_data_dev:
